filebeat.inputs:
- type: log
  paths:
    - /home/pangu/monitor/log/temperature.log
output.elasticsearch:
  hosts: ["212.64.66.113:9201"]
  username: "pangu"
  password: "pg2019axg"
processors:
 - decode_json_fields:
     fields: ["message"]
     process_array: false
     max_depth: 1
     target: ""
     overwrite_keys: false
